name = "edge-chat-demo"
workers_dev = true
compatibility_date = "2021-11-08"
main = "src/echo.mjs"

[durable_objects]
bindings = [
  { name = "echo", class_name = "Echo" },
]

[[rules]]
type = "Data"
globs = ["**/*.html"]
fallthrough = false

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Echo"]
